# Config file for go-test-coverage github action.

profile: coverage.out
local-prefix: "github.com/mrigesh/go-test-coverage-example"
threshold:
  file: 10
  package: 10
  total: 10
override: []
exclude:
  paths:
    - main\.go$
    - csv/
    - env/
    - error/
    - http/
    - jwt/
    - lambda/
    - log/
    - mobile_number/
    - rules/
    - shutdown/